version: '3.9'

services:
  web-prod:
    build: .
    container_name: web-prod
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/Forum
    ports:
      - 8001:8000
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ENGINE=${ENGINE}
      - HOST=${HOST}
      - PORT=${PORT}
      - DB=${DB}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
    networks:
      - forum_network
networks:
  forum_network:
