version: '3.9'

services:
  api-dev:
    build: .
    container_name: api-dev
    restart: on-failure
    command: gunicorn forum.wsgi:application --bind 0.0.0.0:8000
    volumes:
      # - ./:/Forum
      - static:/home/forum/app/public/static
      - media:/home/forum/app/public/media
    ports:
      - 8000:8000
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ENGINE=${ENGINE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - EMAIL_BACKEND=${EMAIL_BACKEND}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST}
    networks:
      - forum_network
  frontend:
    container_name: frontend
    volumes:
      - static:/home/forum/app/public/static
    environment:
      - REACT_APP_BASE_API_URL=${REACT_APP_BASE_API_URL}
      - REACT_APP_PUBLIC_URL=${REACT_APP_PUBLIC_URL}
    ports:
      - 3000:80
    build:
      context: ./FrontEnd
      target: production
    networks:
      - forum_network

networks:
  forum_network:

volumes:
  static:
  media:
