name: Testing BE
on: pull_request

env:
  DEBUG: False
  SECRET_KEY: django-insecure-8p_=_(i8$#=t_n26md(d7=gpc%5sss!4-1a0cp(lir3-0x^$8%
  PG_DB: db
  PG_USER: postgres
  PG_PASSWORD: postgres
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
  EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: 572
  EMAIL_USE_TLS: 1
  EMAIL_HOST_USER: test@test.com
  EMAIL_HOST_PASSWORD: Test1234
  CORS_ORIGIN_WHITELIST: ''
  ALLOWED_ENV_HOST: ''
  REDIS_URL: ${{ vars.REDIS_URL }}
  RECAPTCHA_V2_PRIVATE_KEY: ''
  RECAPTCHA_URL: ${{ vars.RECAPTCHA_URL }}


jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container ?
      postgres:
        # Docker Hub image
        image: postgres:14
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: db
          POSTGRES_PASSWORD: postgres
#        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install ./BackEnd/requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r ./BackEnd/requirements.txt
      - name: Create Migrations
        run: |
          cd BackEnd
          python manage.py makemigrations
          python manage.py migrate
      - name: running tests
        run: |
          cd BackEnd
          python manage.py test --settings=forum.test_setting